// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLvZpnJruni6at-NlQYoUsViFkGzCDEA',
    appId: '1:27959974341:web:7f2c0f46c9d4b0053153ac',
    messagingSenderId: '27959974341',
    projectId: 'tah-lya',
    authDomain: 'tah-lya.firebaseapp.com',
    storageBucket: 'tah-lya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy541FS9TzEfEhlqbPvLXV3598LYLOM5E',
    appId: '1:27959974341:android:d93d5f401260409f3153ac',
    messagingSenderId: '27959974341',
    projectId: 'tah-lya',
    storageBucket: 'tah-lya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-sSoNvxDC4cie1-ME1cJoJVek8YFyX0',
    appId: '1:27959974341:ios:685a9d05db33c0133153ac',
    messagingSenderId: '27959974341',
    projectId: 'tah-lya',
    storageBucket: 'tah-lya.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );
}
